add html ids to jobroles and job spec ui's
rorkainos/Sprint_One_Front pull request #10
Opened 2022-12-01 14:55 UTC by rorkainos

add html ids to jobroles and job spec ui's

2022-12-01 15:05 UTC, mdemartini approved these changes
Great!

2022-12-01 15:09 UTC, shaunganley requested changes

2022-12-01 15:09 UTC, shaunganley commented on app/views/jobroles.html
> +            <td id="{{row.capability}}">{{row.capability}}</td>
I assume these aren't unique field so could possibly be repeated? if so then please add append a loop index or something similar to make it unique

2022-12-01 15:11 UTC, rorkainos commented on app/views/jobroles.html
> +            <td id="{{row.capability}}">{{row.capability}}</td>
they are encapsulated in a unique id row, shouldn't this be fine

2022-12-01 16:24 UTC, shaunganley approved these changes

2022-12-02 13:08 UTC, shaunganley approved these changes

2022-12-02 14:03 UTC, merged