039 UI job roles page
rorkainos/Sprint_One_Front pull request #12
Opened 2022-12-05 09:11 UTC by mdemartini

2022-12-05 09:46 UTC, rorkainos requested changes

2022-12-05 09:46 UTC, rorkainos commented on test/UI/UI_JobRolePage.js
> +})
does the driver.quit in the afterEach not do the same thing as the driver.close on line 40. If so the driver.close could be doing nothing really or the reverse.

2022-12-05 09:46 UTC, rorkainos commented on test/UI/UI_JobRolePage.js
> +
perhaps 'JobRolesCheck' isn't as descriptive as it could be relative to what is being tested here?

2022-12-05 09:53 UTC, mdemartini commented on test/UI/UI_JobRolePage.js
> +
changed to 'should return an error when Job Roles page is not displayed or there is no Job Roles table'

2022-12-05 09:56 UTC, mdemartini commented on test/UI/UI_JobRolePage.js
> +})
driver.close() should close the tab in browser, in this case is only one tab so I moved driver.close() into afterEach()

2022-12-05 11:31 UTC, rorkainos requested changes

2022-12-05 11:31 UTC, rorkainos commented on test/UI/UI_JobRolePage.js
> +
change test name to the good case, ie what are you testing for, if this fails it will tell someone how to fix it. Imagine if you left the company

2022-12-05 14:49 UTC, rorkainos approved these changes

2022-12-05 15:45 UTC, shaunganley requested changes

2022-12-05 15:45 UTC, shaunganley commented on test/UI/UI_JobRolePage.js
> +    await driver.get("http://localhost:3000/jobroles");
could you pass the base URL in as an environment variable so we could easily run against the UI when on AWS

2022-12-05 15:45 UTC, shaunganley commented on test/UI/UI_JobRolePage.js
> +    assert.equal(await driver.findElement(By.xpath("/html[1]/body[1]/h2[1]")).getText(), "List of Job Roles");
you should find by ID rather than xpath

2022-12-06 08:04 UTC, mdemartini commented on test/UI/UI_JobRolePage.js
> +    await driver.get("http://localhost:3000/jobroles");
Added environment variable for url, const because this url won't be changed during test run

2022-12-06 08:05 UTC, mdemartini commented on test/UI/UI_JobRolePage.js
> +    assert.equal(await driver.findElement(By.xpath("/html[1]/body[1]/h2[1]")).getText(), "List of Job Roles");
Waiting for ticket 098 to be done. This page element has no html ID. That's the reason behind using xpath for this one

2022-12-06 15:08 UTC, mdemartini commented on test/UI/UI_JobRolePage.js
> +    assert.equal(await driver.findElement(By.xpath("/html[1]/body[1]/h2[1]")).getText(), "List of Job Roles");
Done

2022-12-07 11:51 UTC, shaunganley requested changes

2022-12-07 11:51 UTC, shaunganley commented on test/UI/UI_JobRolePage.js
> +const jobRolesPageURL = "http://localhost:3000/jobroles";
this should be an environment variable that gets passed in to tests, ask a dev to help you with this

2022-12-07 12:58 UTC, mdemartini commented on test/UI/UI_JobRolePage.js
> +const jobRolesPageURL = "http://localhost:3000/jobroles";
Done. also added lines 52-55 to frontend readme file on how to add environment variable and run selenium test

2022-12-07 13:39 UTC, shaunganley approved these changes

2022-12-07 14:46 UTC, merged