024 registration system
rorkainos/Sprint_One_Front pull request #14
Opened 2022-12-05 16:00 UTC by james-walshe

- Created a registration form page
- Created a GET and POST route 
- Created a user service and validator class with unit tests

2022-12-05 16:13 UTC, andrew-fawcett commented on .vscode/launch.json
> +{
I see the folder this is in is added to your .gitignore, is this meant to be pushed?

2022-12-05 16:15 UTC, andrew-fawcett commented on app/routes.js
> +const js = require('./service/JobService')
Constant for JobService is also declared in line 9, remove one of these and refactor

2022-12-05 16:16 UTC, andrew-fawcett commented on app/routes.js
> +const e = require('express')
Constant for express is also declared in line 1, remove one of these and refactor

2022-12-05 16:17 UTC, andrew-fawcett commented on app/routes.js
> +router.get('/addjobrole', async (req, res) => {
Lines here down to 76 are from user story 012 which hasn't been approved yet, should they be part of this story?

2022-12-05 17:09 UTC, james-walshe commented on .vscode/launch.json
> +{
No, shouldn't be there.

2022-12-05 19:41 UTC, andrew-fawcett approved these changes

2022-12-06 13:54 UTC, shaunganley commented on test/unit/service/UserServiceTests.js
> +            mock.onGet(UserService.REGISTRATION).reply(500);
add a test for 400 being returned from API

2022-12-06 13:55 UTC, shaunganley commented on test/unit/validator/UserValidatorTests.js
> +        it('should return error when password is doesnt include a capital letter', () => {
add test for all upper case password

2022-12-06 16:04 UTC, shaunganley requested changes

2022-12-06 16:04 UTC, shaunganley commented on test/unit/validator/UserValidatorTests.js
> +            expect(UserValidator.validateUser(user).roleError).to.equal(undefined)
are these copy/paste errors?

2022-12-06 16:35 UTC, james-walshe commented on test/unit/validator/UserValidatorTests.js
> +            expect(UserValidator.validateUser(user).roleError).to.equal(undefined)
No, the validateUser method alters the user object causing the following validateUser method to throw an exception.

2022-12-07 12:10 UTC, shaunganley commented on test/unit/validator/UserValidatorTests.js
> +            expect(UserValidator.validateUser(user).roleError).to.equal(undefined)
I think my confusion is that you define the exact same user 3 times, please create 1 user object followed by the 3 expects

2022-12-08 09:46 UTC, shaunganley approved these changes

2022-12-08 14:58 UTC, shaunganley approved these changes

2022-12-08 15:27 UTC, shaunganley approved these changes

2022-12-08 15:32 UTC, merged