002 view job spec
rorkainos/Sprint_One_Front pull request #8
Opened 2022-11-29 11:53 UTC by rorkainos

Display the specification of a job role from the job roles ui by clicking on a particular job role

2022-11-29 14:42 UTC, shaunganley requested changes

2022-11-29 14:42 UTC, shaunganley commented on app/routes.js
> +    let id = req.query.id;
this shouldn't be a query param, you should use /jobspec/:id

2022-11-29 14:42 UTC, shaunganley commented on app/routes.js
> +        }
remove this and pass the object in to the view

2022-11-30 09:47 UTC, shaunganley requested changes

2022-11-30 09:47 UTC, shaunganley commented on app/views/jobSpec.html
> +<h2>Job Specification</h2>
can you add the role name to heading so we know which job spec we're looking at?

2022-11-30 09:47 UTC, shaunganley commented on test/unit/service/JobServiceTests.js
> +        mock.onGet(JobService.GET_JOB_SPEC + '1').reply(() => {return [200, data]});
why is the function needed inside reply, can't you just .reply(200, data) or similar?

2022-11-30 09:47 UTC, shaunganley commented on test/unit/service/JobServiceTests.js
> +        mock.onGet(JobService.GET_JOB_SPEC + '1').reply(500);
create id var rather than hardcoding

2022-11-30 10:45 UTC, rorkainos commented on app/views/jobSpec.html
> +<h2>Job Specification</h2>
I had this in the tab title, just forgot to change good spot

2022-11-30 11:08 UTC, KacperBober approved these changes

2022-11-30 12:04 UTC, shaunganley approved these changes

2022-12-01 14:15 UTC, merged