012 add role
rorkainos/Sprint_One_Front pull request #9
Opened 2022-12-01 09:36 UTC by james-walshe

- Created UI form for adding a new job role.
- Added front end validation and error messages.
- Wrote unit tests for validator and service classes.

2022-12-01 09:58 UTC, rorkainos requested changes

2022-12-01 09:58 UTC, rorkainos commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
I think you should delete this, and add .vscode to your git ignore

2022-12-01 09:58 UTC, rorkainos commented on test/unit/validator/JobRoleValidator.js
> +var chai = require('chai');
add tests to name of this file

2022-12-01 09:58 UTC, rorkainos commented on app/validator/JobRoleValidator.js
> +    let error = {};
instead of returning each time you could continue to get all the errors in one go. Imagine on the ui everything is wrong there user has to change and upload once at a time to get each individual error

2022-12-01 09:58 UTC, rorkainos commented on app/validator/JobRoleValidator.js
> +
perhaps also validate for a blank string

2022-12-01 09:58 UTC, rorkainos commented on app/validator/JobRoleValidator.js
> +            // test if url is valid
very good, I wouldn't of thought of this

2022-12-01 09:58 UTC, rorkainos commented on app/views/addjobrole.html
> +
do this count down the characters like twitter tweet, if so very nice addition

2022-12-01 09:58 UTC, rorkainos commented on test/unit/service/JobServiceTests.js
>  var MockAdapter = require('axios-mock-adapter');
careful with doing git add . as some stuff was pushed that probs shouldn't. you can do git status then git add {file path}

2022-12-01 09:58 UTC, rorkainos commented on test/unit/validator/JobRoleValidator.js
> +                bandLevel: 2
if this was " " it would have passed. I think here you can do something like String.trim(), removes whitespaces either side of the main string ie " test test " becomes "test test"

2022-12-01 09:58 UTC, rorkainos commented on test/unit/validator/JobRoleValidator.js
> +                jobSpec: "awawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawawa
I think here you should just look up some String creation library that allows you to pass a number which will be the length of the string, will look cleaner

2022-12-01 10:03 UTC, james-walshe commented on app/views/addjobrole.html
> +
yeah nifty enough

2022-12-01 12:07 UTC, rorkainos approved these changes

2022-12-01 13:28 UTC, shaunganley requested changes
great work, just a few small comments

2022-12-01 13:28 UTC, shaunganley commented on app/routes.js
> +        js.insertJobRole(req.body)
what happens when this fails? should be surrounded with a try/catch

2022-12-01 13:28 UTC, shaunganley commented on app/service/JobService.js
> +module.exports.POST_JOB_ROLE = '/hr/job-roles';
these will always be the same, just make var generic job roles

2022-12-01 13:28 UTC, shaunganley commented on app/service/JobService.js
> +        return response;
I don't think you will be using the response from this call so no need to return anything

2022-12-01 14:08 UTC, james-walshe commented on app/service/JobService.js
> +        return response;
Needed currently to test for a 201 status code. Is there a better way to do this?

2022-12-02 13:46 UTC, shaunganley approved these changes

2022-12-07 13:57 UTC, merged